using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;

class LayoutInstaller
{
    const string SymbolsPath = "/usr/share/X11/xkb/symbols/";
    const string RulesPath = "/usr/share/X11/xkb/rules/";

    string AppPath = AppContext.BaseDirectory;
    string DllPath = string.Empty;
    string TargetFilePath = string.Empty;
    string TempFilePath = string.Empty;

    string Lang = string.Empty;
    string Variant = string.Empty;
    string Desc = string.Empty;

    public bool IsVariantPresent(string lang, string variant)
    {
        string text = File.ReadAllText($"{SymbolsPath}{lang}");

        return text.Contains($"// XKBLC {lang} {variant} start");
    }

    public void Install(List<Key> keys, string lang, string variant, string desc)
    {
        Lang = lang.ToLower();
        Variant = variant.ToLower();
        Desc = desc;
        DllPath = System.IO.Path.Combine($"{AppPath}/Elevated", "LayoutInstall.dll");

        BackupFiles();
        TargetFilePath = $"{SymbolsPath}{lang}";

        LayoutGenerator lg = new();
        lg.Generate(keys, Lang, Variant, Desc);

        InstallXkb();
        InstallLst();
    }

    public void Delete(string lang, string variant)
    {
        Lang = lang;
        Variant = variant;

        DeleteXkb(Lang, Variant);
        DeleteLst();
    }

    public void DeleteXkb(string lang, string variant)
    {
        TargetFilePath = $"{SymbolsPath}{lang}";
        DllPath = System.IO.Path.Combine($"{AppPath}/Elevated", "LayoutInstall.dll");

        string filePath = $"{SymbolsPath}{Lang}";

        if (!File.Exists(filePath))
        {
            Console.WriteLine("File doesn't exist");
            Console.WriteLine($"Provided Path: {filePath}");
            return;
        }

        string genMarker = "// Generated by XkbLayoutCreator (github: Bread92)";
        string blockStartMarker = $"// XKBLC {lang} {variant} start";
        string endMarker = "// XKBLC end";

        var lines = File.ReadAllLines(filePath);
        var output = new List<string>(lines.Length);

        bool skipping = false;

        foreach (var line in lines)
        {
            if (!skipping)
            {
                if (line.Contains(genMarker) || 
                    line.Contains(blockStartMarker))
                {
                    skipping = true;
                    continue;
                }

                output.Add(line);
                continue;
            }

            // Inside generated block
            if (line.Contains(endMarker))
            {
                skipping = false;
                continue;
            }
        }

        File.WriteAllLines("temp.xkb", output);

        string projectDir = AppContext.BaseDirectory;
        TempFilePath = $"{projectDir}../../../temp.xkb";

        WriteElevated();

        File.Delete(TempFilePath);
    }

    void InstallXkb()
    {
        StringBuilder sb = new();

        string projectDir = AppContext.BaseDirectory;

        if(TempFilePath == string.Empty)
            TempFilePath = $"{projectDir}../../../{Lang}_{Variant}.xkb";

        sb.Append(File.ReadAllText($"{SymbolsPath}{Lang}"));

        // Guards are used to detect where in the file is the layout
        // to be able to update/delete it
        sb.AppendLine("\n// Generated by XkbLayoutCreator (github: Bread92)");
        sb.AppendLine("// DO NOT DELETE THIS COMMENT");
        sb.AppendLine("// It is used for detection");
        sb.AppendLine($"// XKBLC {Lang} {Variant} start");

        // Copy generated .xkb file and append the new layout to it
        sb.Append(File.ReadAllText($"{Lang}_{Variant}.xkb"));

        sb.AppendLine("// XKBLC end");

        File.WriteAllText($"{Lang}_{Variant}.xkb", sb.ToString());

        Console.WriteLine($"\nprojectDir = {projectDir}\n");
        Console.WriteLine("TempFilePath = " + TempFilePath);

        WriteElevated();
    }

    void InstallLst()
    {
        var lines = File.ReadAllLines($"{RulesPath}/evdev.lst").ToList();

        string insertLine = $"{Variant}\t\t{Lang}: {Desc}";

        int index = lines.FindIndex(l => l == "! variant");

        lines.Insert(index + 1, $"  {Variant} {Lang}: {Desc}  ;Generated by XKBLC (Do not delete the comment!)");

        TargetFilePath = $"{RulesPath}evdev.lst";

        string projectDir = AppContext.BaseDirectory;
        TempFilePath = $"{projectDir}../../../temp.lst";

        File.WriteAllLines(TempFilePath, lines);

        WriteElevated();

        File.Delete(TempFilePath);
    }

    void DeleteLst()
    {
        var lines = File.ReadAllLines($"{RulesPath}/evdev.lst").ToList();

        int index = lines.FindIndex(l => l.Contains(Variant) &&
                    l.Contains(Lang) &&
                    l.Contains($"XKBLC"));

        lines.RemoveAt(index);

        TempFilePath = $"{AppContext.BaseDirectory}../../../temp.lst";
        TargetFilePath = $"{RulesPath}evdev.lst";

        File.WriteAllLines(TempFilePath, lines);

        WriteElevated();

        File.Delete(TempFilePath);
    }

    void WriteElevated()
    {
        var psi = new ProcessStartInfo
        {
            FileName = "pkexec",
                     UseShellExecute = false
        };

        psi.ArgumentList.Add("/usr/bin/dotnet");
        psi.ArgumentList.Add(DllPath);
        psi.ArgumentList.Add(TargetFilePath); // Target
        psi.ArgumentList.Add(TempFilePath); // Source

        Process.Start(psi)?.WaitForExit();
    }

    void BackupFiles()
    {
        string projectDir = AppContext.BaseDirectory;
        string backupDir = Path.Combine(projectDir, "Backups");

        Directory.CreateDirectory(backupDir);
        Directory.CreateDirectory(Path.Combine(backupDir, "symbols"));
        Directory.CreateDirectory(Path.Combine(backupDir, "rules"));

        CopyIfMissing(
                $"{SymbolsPath}{Lang}",
                Path.Combine(backupDir, "symbols", $"{Lang}.bak"));

        CopyIfMissing(
                $"{RulesPath}evdev.lst",
                Path.Combine(backupDir, "rules", "evdev.lst.bak"));

        CopyIfMissing(
                $"{RulesPath}evdev.xml",
                Path.Combine(backupDir, "rules", "evdev.xml.bak"));
    }

    void CopyIfMissing(string source, string destination)
    {
        if (!File.Exists(source))
            return;

        if (File.Exists(destination))
            return;

        File.Copy(source, destination, overwrite: false);
    }
}
