using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Xml.Linq;
using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable CS8632

class LayoutManager
{
    string SymbolsPath = "/usr/share/X11/xkb/symbols/";
    string RulesPath = "/usr/share/X11/xkb/rules/";

    string AppPath = AppContext.BaseDirectory;
    string DllPath = string.Empty;

    string XkbTarget = string.Empty;
    string LstTarget = string.Empty;
    string XmlTarget = string.Empty;
    string XkbTemp = string.Empty;
    string LstTemp = string.Empty;
    string XmlTemp = string.Empty;

    string Lang = string.Empty;
    string Variant = string.Empty;
    string Desc = string.Empty;

    public LayoutManager(string xkbPath)
    {
        SymbolsPath = System.IO.Path.Combine(xkbPath, "symbols");
        RulesPath = System.IO.Path.Combine(xkbPath, "rules");
    }

    public bool IsVariantPresent(string lang, string variant)
    {
        string text = File.ReadAllText($"{SymbolsPath}/{lang}");

        return text.Contains($"// XKBLC {lang} {variant} start");
    }

    public void Install(Layout layout)
    {
        Lang = layout.Lang.ToLower();
        Variant = layout.Variant.ToLower();
        Desc = layout.Desc;
        DllPath = System.IO.Path.Combine($"{AppPath}/Elevated", "LayoutInstall.dll");

        BackupFiles();

        LayoutGenerator lg = new();
        lg.Generate(layout, "temp.xkb", "temp.xml");

        PrepXkb();
        PrepLst();
        PrepXml();

        Console.WriteLine(XkbTarget);
        Console.WriteLine(XkbTemp);
        Console.WriteLine(LstTarget);
        Console.WriteLine(LstTemp);
        Console.WriteLine(XmlTarget);
        Console.WriteLine(XmlTemp);

        WriteElevated();

        File.Delete(XkbTemp);
        File.Delete(LstTemp);
        File.Delete(XmlTemp);
    }

    public void Delete(string lang, string variant)
    {
        Lang = lang;
        Variant = variant;
        DllPath = System.IO.Path.Combine($"{AppPath}/Elevated", "LayoutInstall.dll");

        PrepDeleteXkb();
        PrepDeleteLst();
        PrepDeleteXml();

        Console.WriteLine(XkbTarget);
        Console.WriteLine(XkbTemp);
        Console.WriteLine(LstTarget);
        Console.WriteLine(LstTemp);
        Console.WriteLine(XmlTarget);
        Console.WriteLine(XmlTemp);

        WriteElevated();

        File.Delete(XkbTemp);
        File.Delete(LstTemp);
        File.Delete(XmlTemp);
    }

    public void PrepDeleteXkb()
    {
        XkbTarget = $"{SymbolsPath}/{Lang}";

        if (!File.Exists(XkbTarget))
        {
            Console.WriteLine("File doesn't exist");
            Console.WriteLine($"Provided Path: {XkbTarget}");
            return;
        }

        string genMarker = "// Generated by XkbLayoutCreator (github: Bread92)";
        string blockStartMarker = $"// XKBLC {Lang} {Variant} start";
        string endMarker = "// XKBLC end";

        var lines = File.ReadAllLines(XkbTarget);
        var output = new List<string>(lines.Length);

        bool skipping = false;

        foreach (var line in lines)
        {
            if (!skipping)
            {
                if (line.Contains(genMarker))
                {
                    skipping = true;
                    continue;
                }

                output.Add(line);
                continue;
            }

            // Inside generated block
            if (line.Contains(endMarker))
            {
                skipping = false;
                continue;
            }
        }

        File.WriteAllLines("temp.xkb", output);

        string projectDir = AppContext.BaseDirectory;
        XkbTemp = $"{projectDir}../../../temp.xkb";
    }

    void PrepXkb()
    {
        const string tempName = "temp.xkb";
        string projectDir = AppContext.BaseDirectory;

        StringBuilder sb = new();

        if(XkbTemp == string.Empty)
            XkbTemp = $"{projectDir}../../../{tempName}";

        sb.Append(File.ReadAllText($"{SymbolsPath}/{Lang}"));

        // Guards are used to detect where in the file is the layout
        // to be able to update/delete it
        sb.AppendLine("// Generated by XkbLayoutCreator (github: Bread92)");
        sb.AppendLine("// DO NOT DELETE THIS COMMENT");
        sb.AppendLine("// It is used for detection");
        sb.AppendLine($"// XKBLC {Lang} {Variant} start");

        // Copy generated .xkb file and append the new layout to it
        sb.Append(File.ReadAllText(XkbTemp));

        sb.AppendLine("// XKBLC end");

        File.WriteAllText(XkbTemp, sb.ToString());

        Console.WriteLine($"\nprojectDir = {projectDir}\n");
        Console.WriteLine("XkbTemp = " + XkbTemp);

        XkbTarget = $"{SymbolsPath}/{Lang}";
    }

    void PrepLst()
    {
        const string tempName = "temp.lst";

        var lines = File.ReadAllLines($"{RulesPath}/evdev.lst").ToList();

        string insertLine = $"{Variant}\t\t{Lang}: {Desc}";

        int index = lines.FindIndex(l => l == "! variant");

        lines.Insert(index + 1, $"  {Variant} {Lang}: {Desc}  ;Generated by XKBLC (Do not delete the comment!)");

        LstTarget = $"{RulesPath}/evdev.lst";

        string projectDir = AppContext.BaseDirectory;
        LstTemp = $"{projectDir}../../../{tempName}";

        File.WriteAllLines(LstTemp, lines);
    }

    void PrepXml()
    {
        const string tempName = "temp.xml";

        string projectDir = AppContext.BaseDirectory;
        XmlTemp = $"{projectDir}../../../{tempName}";

        File.Copy($"{RulesPath}/evdev.xml", XmlTemp, true);

        var doc = XDocument.Load(XmlTemp);
        var layout = doc.Descendants("layout")
            .FirstOrDefault(l => (string?)l.Element("configItem")?.Element("name") == Lang);

        if (layout == null)
            return;

        var variantList = layout.Element("variantList");
        if (variantList == null)
        {
            variantList = new XElement("variantList");
            layout.Add(variantList);
        }

        var newVariant = new XElement("variant",
                new XElement("configItem",
                    new XElement("name", Variant),
                    new XElement("description", Desc)
                    )
                );

        variantList.Add(newVariant);

        doc.Save(XmlTemp);

        XmlTarget = $"{RulesPath}/evdev.xml";
    }

    void PrepDeleteXml()
    {
        string projectDir = AppContext.BaseDirectory;
        XmlTemp = $"{projectDir}temp.xml";

        File.Copy($"{RulesPath}/evdev.xml", XmlTemp, true);

        var doc = XDocument.Load(XmlTemp);

        var layout = doc.Descendants("layout")
            .FirstOrDefault(l => (string?)l.Element("configItem")?.Element("name") == Lang);

        if (layout == null)
            return;

        var variantList = layout.Element("variantList");
        if (variantList == null)
            return;

        var toRemove = variantList.Elements("variant")
            .FirstOrDefault(v => (string?)v.Element("configItem")?.Element("name") == Variant);

        toRemove?.Remove();

        doc.Save(XmlTemp);

        XmlTarget = $"{RulesPath}/evdev.xml";
    }

    void PrepDeleteLst()
    {
        var lines = File.ReadAllLines($"{RulesPath}/evdev.lst").ToList();

        int index = lines.FindIndex(l => l.Contains(Variant) &&
                    l.Contains(Lang) &&
                    l.Contains($"XKBLC"));

        lines.RemoveAt(index);

        LstTemp = $"{AppContext.BaseDirectory}../../../temp.lst";
        LstTarget = $"{RulesPath}evdev.lst";

        File.WriteAllLines(LstTemp, lines);
    }

    void WriteElevated()
    {
        var psi = new ProcessStartInfo
        {
            FileName = "pkexec",
                     UseShellExecute = false
        };

        psi.ArgumentList.Add("/usr/bin/dotnet");
        psi.ArgumentList.Add(DllPath);
        psi.ArgumentList.Add(XkbTarget); // Target
        psi.ArgumentList.Add(XkbTemp); // Source
        psi.ArgumentList.Add(LstTarget); // Target
        psi.ArgumentList.Add(LstTemp); // Source
        psi.ArgumentList.Add(XmlTarget); // Target
        psi.ArgumentList.Add(XmlTemp); // Source

        Process.Start(psi)?.WaitForExit();
    }

    void BackupFiles()
    {
        string projectDir = AppContext.BaseDirectory;
        string backupDir = Path.Combine(projectDir, "Backups");

        Directory.CreateDirectory(backupDir);
        Directory.CreateDirectory(Path.Combine(backupDir, "symbols"));
        Directory.CreateDirectory(Path.Combine(backupDir, "rules"));

        CopyIfMissing(
                $"{SymbolsPath}/{Lang}",
                Path.Combine(backupDir, "symbols", $"{Lang}.bak"));

        CopyIfMissing(
                $"{RulesPath}/evdev.lst",
                Path.Combine(backupDir, "rules", "evdev.lst.bak"));

        CopyIfMissing(
                $"{RulesPath}/evdev.xml",
                Path.Combine(backupDir, "rules", "evdev.xml.bak"));
    }

    void CopyIfMissing(string source, string destination)
    {
        if (!File.Exists(source))
            return;

        if (File.Exists(destination))
            return;

        File.Copy(source, destination, overwrite: false);
    }
}
